modLoader = "javafml"
loaderVersion = "[37,)"
#issueTrackerURL = ""
license = "GNU"

[[mods]]
modId = "mca"
version = "${version}"
displayName = "Minecraft Comes Alive"
authors = "Luke100000, S0llace, CDAGaming, ffrannny, jahx_senpoopie, WildBamaBoy, SheWolfDeadly"
description = '''
No more squidward-villagers! Interact with male and female human villagers and raise a family.
'''
logoFile = "mca.png"

[[dependencies.mca]]
    modId="forge"
    mandatory=true
    versionRange="[37.1.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mca]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mca]]
    modId="architectury"
    mandatory=true
    versionRange="[2.10.12,)"
    ordering="AFTER"
    side="BOTH"
