modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "GNU"

[[mods]]
modId = "mca"
version = "${version}"
displayName = "Minecraft Comes Alive"
authors = "WildBamaBoy, SheWolfDeadly"
description = '''
No more squidward-villagers! Interact with male and female human villagers and raise a family.
'''
#logoFile = "mca.png"
