name: Java CI with Gradle

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MODRINTH_TOKEN: ${{ secrets.MR_API_TOKEN }}
      CURSEFORGE_TOKEN: ${{ secrets.CF_API_TOKEN }}
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Fetch Tags
        run: git fetch --unshallow --tags
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Artifacts with Gradle
        run: ./gradlew build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: ./build/libs/
      - name: Get tag
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        id: tag
        uses: dawidd6/action-get-tag@v1
      - uses: jungwinter/split@v2
        id: split
        with:
          separator: "+"
          msg: ${{steps.tag.outputs.tag}}
      - name: "Upload to Distributors"
        uses: Kir-Antipov/mc-publish@v3.1
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        with:
          modrinth-id: 1W98a849
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 535291
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

          name: "[Universal ${{steps.split.outputs._1}}] MCA Reborn - ${{steps.split.outputs._0}}"
          changelog-file: changelog.md
          version-type: release
          files-primary: build/libs/*-@(universal).jar
          files-secondary: build/libs/*-@(dev|sources).jar
          loaders: |
            fabric
            forge
            quilt
          java: |
            Java 17
          dependencies: |
            fabric-api | depends | *
            architectury-api | depends | *