name: Java CI with Gradle

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MODRINTH_TOKEN: ${{ secrets.MR_API_TOKEN }}
    if: startsWith(github.ref, 'refs/tags/') # uncomment to execute build for every push
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Get tag
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: "Upload Forge to Modrinth"
        run: ./gradlew :forge:modrinth --stacktrace
      - name: "Upload Fabric to Modrinth"
        run: ./gradlew :fabric:modrinth --stacktrace
      
