name: Java CI with Gradle

on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MODRINTH_TOKEN: ${{ secrets.MR_API_TOKEN }}
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Fetch Tags
        run: git fetch --unshallow --tags
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle - Forge
        run: ./gradlew :forge:build
      - name: Build with Gradle - Fabric
        run: ./gradlew :fabric:build
      - name: Upload Artifacts - Forge
        uses: actions/upload-artifact@v2
        with:
          name: forge_artifacts
          path: ./forge/build/libs/
      - name: Upload Artifacts - Fabric
        uses: actions/upload-artifact@v2
        with:
          name: fabric_artifacts
          path: ./fabric/build/libs/
      - name: Get tag
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        id: tag
        uses: dawidd6/action-get-tag@v1
      - uses: jungwinter/split@v2
        id: split
        with:
          separator: "+"
          msg: ${{steps.tag.outputs.tag}}
      - name: "Upload Fabric to Modrinth"
        run: ./gradlew :fabric:modrinth
      - name: "Upload Forge to Modrinth"
        run: ./gradlew :forge:modrinth
      - name: "Upload Fabric to CurseForge"
        uses: itsmeow/curseforge-upload@v3
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        with:
          file_path: "fabric/build/libs/minecraft-comes-alive-${{steps.tag.outputs.tag}}-fabric.jar"
          display_name: "[Fabric 1.19.2] MCA Reborn - ${{steps.split.outputs._0}}"
          game_endpoint: "minecraft"
          relations: "fabric-api:requiredDependency,architectury-api:requiredDependency"
          game_versions: "Minecraft 1.19:1.19.2,Java 17,Fabric"
          project_id: "535291"
          token: "${{ secrets.CF_API_TOKEN }}"
          changelog_type: "markdown"
          changelog: "Full changelog can be found in the [GitHub Repo](https://github.com/Luke100000/minecraft-comes-alive/blob/1.19.2/changelog.md)"
          release_type: "release"
      - name: "Upload Forge to CurseForge"
        uses: itsmeow/curseforge-upload@v3
        if: ${{ success() && startsWith(github.ref, 'refs/tags/') }}
        with:
          file_path: "forge/build/libs/minecraft-comes-alive-${{steps.tag.outputs.tag}}-forge.jar"
          display_name: "[Forge 1.19.2] MCA Reborn - ${{steps.split.outputs._0}}"
          game_endpoint: "minecraft"
          relations: "architectury-api:requiredDependency"
          game_versions: "Minecraft 1.19:1.19.2,Java 17,Forge"
          project_id: "535291"
          token: "${{ secrets.CF_API_TOKEN }}"
          changelog_type: "markdown"
          changelog: "Full changelog can be found in the [GitHub Repo](https://github.com/Luke100000/minecraft-comes-alive/blob/1.19.2/changelog.md)"
          release_type: "release"
